[build]
  command = "next build"
  publish = "out"
  functions = "functions"

# Redirects
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Rewrite all other routes to the index.html file
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
